Routers & Security-Groups
ist-dsi/scala-neutron-client pull request #2
Opened 2020-07-04 14:13 UTC by afonsomatos

Added Routers, Security-Groups and Security-Group-Roles services and models.
I left integration tests to the end because that's what made sense, since we first want to agree on a pleasant programming interface  to use.

Here are the implemented and missing services:
```
Neutron (Network):

[Simão]

     GET   /v2.0/quotas                        List quotas for projects with non-default quota values
     GET   /v2.0/quotas/{project_id}           List quotas for a project
     PUT   /v2.0/quotas/{project_id}           Update quota for a project
  DELETE   /v2.0/quotas/{project_id}           Reset quota for a project
     GET   /v2.0/quotas/{project_id}/default   List default quotas for a project

[Me]

X    GET   /v2.0/security-groups                       List security groups
X   POST   /v2.0/security-groups                       Create security group
X    GET   /v2.0/security-groups/{security_group_id}   Show security group
X    PUT   /v2.0/security-groups/{security_group_id}   Update security group
X DELETE   /v2.0/security-groups/{security_group_id}   Delete security group

X    GET   /v2.0/security-group-rules                            List security group rules
X   POST   /v2.0/security-group-rules                            Create security group rule
X    GET   /v2.0/security-group-rules/{security_group_rule_id}   Show security group rule
X DELETE   /v2.0/security-group-rules/{security_group_rule_id}   Delete security group rule

X    GET   /v2.0/networks/{network_id}    Show network details
X    PUT   /v2.0/networks/{network_id}    Update network
X DELETE   /v2.0/networks/{network_id}    Delete network
X    GET   /v2.0/networks                 List networks
X       - Lots of query parameters can be made into methods
X   POST   /v2.0/networks                 Create network
X   POST   /v2.0/networks                 Bulk Create network

X    GET   /v2.0/ports/{port_id}  Show port details
X    PUT   /v2.0/ports/{port_id}  Update port
X DELETE   /v2.0/ports/{port_id}  Delete port
X    GET   /v2.0/ports            List ports
X   POST   /v2.0/ports            Create port

X    GET   /v2.0/floatingips                   List floating IPs
X   POST   /v2.0/floatingips                   Create floating IP
X    GET   /v2.0/floatingips/{floatingip_id}   Show floating IP details
X    PUT   /v2.0/floatingips/{floatingip_id}   Update floating IP
X DELETE   /v2.0/floatingips/{floatingip_id}   Delete floating IP

X    GET   /v2.0/routers                List routers
X   POST   /v2.0/routers                Create router
X    GET   /v2.0/routers/{router_id}    Show router details
X    PUT   /v2.0/routers/{router_id}    Update router
X DELETE   /v2.0/routers/{router_id}    Delete router

X    PUT   /v2.0/routers/{router_id}/add_router_interface       Add interface to router
X    PUT   /v2.0/routers/{router_id}/remove_router_interface    Remove interface from router
X    PUT   /v2.0/routers/{router_id}/add_extraroutes            Add extra routes to router
X    PUT   /v2.0/routers/{router_id}/remove_extraroutes         Remove extra routes from router

X     GET   /v2.0/subnets               List subnets
X    POST   /v2.0/subnets               Create subnet
X    POST   /v2.0/subnets               Bulk create subnet
X     GET   /v2.0/subnets/{subnet_id}   Show subnet details
X     PUT   /v2.0/subnets/{subnet_id}   Update subnet
X  DELETE   /v2.0/subnets/{subnet_id}   Delete subnet
```

2020-07-04 16:01 UTC, Lasering requested changes

2020-07-04 16:01 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/NeutronClient.scala
Aposto que estas 3 linhas não compilam.

2020-07-04 16:01 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/NeutronClient.scala
> +
Aqui dá para ver aquela inconsistência que tinha falado. O SecurityGroupRules e Routers têm uma classe service dedicada os restantes não.

2020-07-04 16:01 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/NeutronClient.scala
>    val uri: Uri = baseUri / "v2.0"
Vais precisar de ter isto para conseguir correr testes.
```scala
val uri: Uri = if (baseUri.path.endsWith("v2.0") || baseUri.path.endsWith("v2.0/")) baseUri else baseUri / "v2.0"
```

2020-07-04 16:01 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/models/FloatingIp.scala
> +
Mete o companion object por cima da companion classe correspondente.

2020-07-04 16:01 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/models/FloatingIp.scala
> +  case class Create(
Não devia ter tudo default value None?

2020-07-04 16:01 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/models/FloatingIp.scala
> +    fixedIpAddress: Option[String],
`fixedIpAddress` e `floatingIpAddress` deviam ser do tipo `InetAddress`.

Consegues fazer um decoder usando a função `InetAddress.getByName`.

2020-07-04 16:01 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/models/FloatingIp.scala
> +    portForwardings: List[Map[String, String]]
O tipo de `portForwardings` parece-me errado.

2020-07-04 16:01 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/models/FloatingIp.scala
> +  case class Read(
Não gosto muito desta classe se chamar `Read`.

2020-07-04 16:01 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/models/Network.scala
> +        network                  <- c.as[Read](deriveDecoder(renaming.snakeCase))
Não parece que isto vá funcionar.

2020-07-04 16:01 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/models/Route.scala
> +  implicit val encoder: Encoder[Route] = deriveEncoder(renaming.snakeCase)
Não podias fazer o codec directamente?

2020-07-04 16:01 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/models/Router.scala
> +    nexthop: String, // Ipv4Address
Garantidamente IPv4? Se sim podes usar `Inet4Address`.

2020-07-04 16:01 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/models/Router.scala
> +
O mesmo que disse para o FloatingIP sobre os companion objects. E não gostar da classe chamar-se Read. E não teres default values = None no `Create` e no `Update`.

2020-07-04 16:01 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/models/RouterInterface.scala
> +
Nones?

2020-07-04 16:01 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/models/SecurityGroup.scala
> +
O mesmo de cima

2020-07-04 16:01 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/models/SecurityGroupRule.scala
> +    ehtertype: Option[String],
Typo? não devia ser `etherType`?

2020-07-04 16:01 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/services/Routers.scala
> +  (implicit e: Encoder[Router#Create], f: Encoder[Router#Update], g: Decoder[Router#Read])
Precisas destes implicitos?

2020-07-04 18:49 UTC, afonsomatos commented on src/main/scala/pt/tecnico/dsi/neutron/NeutronClient.scala
Compilam, porquê?

2020-07-04 19:00 UTC, afonsomatos commented on src/main/scala/pt/tecnico/dsi/neutron/models/Network.scala
> +        network                  <- c.as[Read](deriveDecoder(renaming.snakeCase))
Sugestão?

2020-07-04 19:01 UTC, afonsomatos commented on src/main/scala/pt/tecnico/dsi/neutron/models/FloatingIp.scala
> +
Não dá. Estou a usar um `sealed trait` com o nome.

2020-07-04 19:06 UTC, afonsomatos commented on src/main/scala/pt/tecnico/dsi/neutron/models/FloatingIp.scala
> +  case class Read(
Sugestão?

2020-07-04 19:08 UTC, afonsomatos commented on src/main/scala/pt/tecnico/dsi/neutron/models/Router.scala
> +
Nones fixed. Sugestão para o resto?

2020-07-04 19:17 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/services/Networks.scala
> +final class Networks[F[_]: Sync: Client](baseUri: Uri, authToken: Header)
Codacy found an issue: [Redundant braces after class definition](https://app.codacy.com/gh/ist-dsi/scala-neutron-client/pullRequest?prid=5802728)

2020-07-04 19:18 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/services/FloatingIps.scala
> +final class FloatingIps[F[_]: Sync: Client](baseUri: Uri, authToken: Header)
Codacy found an issue: [Redundant braces after class definition](https://app.codacy.com/gh/ist-dsi/scala-neutron-client/pullRequest?prid=5802728)

2020-07-04 19:18 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/services/SecurityGroups.scala
> +final class SecurityGroups[F[_]: Sync: Client](baseUri: Uri, authToken: Header)
Codacy found an issue: [Redundant braces after class definition](https://app.codacy.com/gh/ist-dsi/scala-neutron-client/pullRequest?prid=5802728)

2020-07-04 19:18 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/services/Subnets.scala
> +final class Subnets[F[_]: Sync: Client](baseUri: Uri, authToken: Header)
Codacy found an issue: [Redundant braces after class definition](https://app.codacy.com/gh/ist-dsi/scala-neutron-client/pullRequest?prid=5802728)

2020-07-04 19:18 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/services/Ports.scala
> +final class Ports[F[_]: Sync: Client](baseUri: Uri, authToken: Header)
Codacy found an issue: [Redundant braces after class definition](https://app.codacy.com/gh/ist-dsi/scala-neutron-client/pullRequest?prid=5802728)

2020-07-04 19:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/services/SecurityGroups.scala
> +final class SecurityGroups[F[_]: Sync: Client](baseUri: Uri, authToken: Header)
Codacy found an issue: [Redundant braces after class definition](https://app.codacy.com/gh/ist-dsi/scala-neutron-client/pullRequest?prid=5802728)

2020-07-04 19:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/services/Networks.scala
> +final class Networks[F[_]: Sync: Client](baseUri: Uri, authToken: Header)
Codacy found an issue: [Redundant braces after class definition](https://app.codacy.com/gh/ist-dsi/scala-neutron-client/pullRequest?prid=5802728)

2020-07-04 19:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/models/package.scala
> +import java.net.Inet4Address
Codacy found an issue: [Use brackets to group imports from the same package](https://app.codacy.com/gh/ist-dsi/scala-neutron-client/pullRequest?prid=5802728)

2020-07-04 19:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/services/Subnets.scala
> +final class Subnets[F[_]: Sync: Client](baseUri: Uri, authToken: Header)
Codacy found an issue: [Redundant braces after class definition](https://app.codacy.com/gh/ist-dsi/scala-neutron-client/pullRequest?prid=5802728)

2020-07-04 19:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/services/Ports.scala
> +final class Ports[F[_]: Sync: Client](baseUri: Uri, authToken: Header)
Codacy found an issue: [Redundant braces after class definition](https://app.codacy.com/gh/ist-dsi/scala-neutron-client/pullRequest?prid=5802728)

2020-07-04 19:24 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/services/FloatingIps.scala
> +final class FloatingIps[F[_]: Sync: Client](baseUri: Uri, authToken: Header)
Codacy found an issue: [Redundant braces after class definition](https://app.codacy.com/gh/ist-dsi/scala-neutron-client/pullRequest?prid=5802728)

2020-07-04 19:26 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/services/FloatingIps.scala
> +final class FloatingIps[F[_]: Sync: Client](baseUri: Uri, authToken: Header)
Codacy found an issue: [Redundant braces after class definition](https://app.codacy.com/gh/ist-dsi/scala-neutron-client/pullRequest?prid=5802728)

2020-07-04 19:26 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/models/package.scala
> +import java.net.Inet4Address
Codacy found an issue: [Use brackets to group imports from the same package](https://app.codacy.com/gh/ist-dsi/scala-neutron-client/pullRequest?prid=5802728)

2020-07-04 19:40 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/models/FloatingIp.scala
> +
Tem que dar, ou não me expliquei bem, ou não estou a perceber o problema.
O que estava a dizer era:
```scala
object FloatingIp {
 object Read { ... }
 case class Read(...)

 object Update { ... }
 case class Update(...)

 object Create { ... }
 case class Create(...)
}
```

2020-07-04 22:54 UTC, afonsomatos commented on src/main/scala/pt/tecnico/dsi/neutron/models/FloatingIp.scala
> +
Ah ok, percebi mal.

2020-07-05 01:11 UTC, Lasering approved these changes

2020-07-05 01:11 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/models/FloatingIp.scala
> +  case class Read(
Não sei, eu percebi porque é que lhe chamaste Read, mas não gosto. Eu continuo a dizer que a class Model não está a acrescentar valor.

2020-07-06 21:56 UTC, merged