Remove WithId
ist-dsi/scala-neutron-client pull request #7
Opened 2020-07-30 20:50 UTC by afonsomatos

2020-07-30 20:53 UTC, afonsomatos commented on src/test/scala/pt/tecnico/dsi/neutron/CrudSpec.scala
> +      stub => service.get(stub.id).idempotently(_.get shouldBe stub)
This is acceptable. This is an integration test and the optional should be `Some`. If it's not, the test is not passing anyways...

2020-07-30 21:25 UTC, Lasering requested changes

2020-07-30 21:25 UTC, Lasering commented on src/main/scala/pt/tecnico/dsi/neutron/services/SecurityGroupRules.scala
The apply method is missing.

2020-07-30 21:25 UTC, Lasering commented on src/test/scala/pt/tecnico/dsi/neutron/CrudSpec.scala
> +      stub => service.get(stub.id).idempotently(_.get shouldBe stub)
```suggestion
      stub => service.get(stub.id).idempotently(_.value shouldBe stub)
```
You need to extend OptionValues to use `.value`. You can read [here](https://www.scalatest.org/user_guide/using_OptionValues) to understand why its better than a `.get`.

2020-07-30 21:25 UTC, Lasering commented on src/test/scala/pt/tecnico/dsi/neutron/CrudSpec.scala
> +      stub => service.get(stub.id).idempotently(_.get shouldBe stub)
This would also be a good use case for the `apply` method.

2020-07-30 21:25 UTC, Lasering commented on src/test/scala/pt/tecnico/dsi/neutron/CrudSpec.scala
> +      } yield assert(fetchedStubs.zip(createdStubs).forall { case (a, b) => a.get == b })
Same as the comment above.

2020-08-01 11:20 UTC, afonsomatos commented on src/test/scala/pt/tecnico/dsi/neutron/CrudSpec.scala
> +      stub => service.get(stub.id).idempotently(_.get shouldBe stub)
True, maybe in the the common's CrudService?

2020-08-01 11:27 UTC, merged